version: '3.9'

services:

  mongo_db:
    container_name: db_container_product
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db

  api:
    build: .
    ports:
      - 8002:8002
    environment:
      PORT: 8002
      DB_URL: mongodb://mongo_db:27017/richylife_product_ms
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
